name: Execute Snowflake Code

on:
  push:
    branches:
      - main

jobs:
  run-snowflake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install snowflake-connector-python

      - name: Execute SQL on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}       # Value: RX58491.ap-south-1
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}             # Value: ANKIT210203
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}     # Value: G77QX8jFht9RuuM
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}     # Value: DEMO
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}         # Value: PUBLIC
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}   # Value: SNOWFLAKE_LEARNING_WH
        run: |
          python3 -c "
import snowflake.connector
conn = snowflake.connector.connect(
    user='${{ secrets.SNOWFLAKE_USER }}',
    password='${{ secrets.SNOWFLAKE_PASSWORD }}',
    account='${{ secrets.SNOWFLAKE_ACCOUNT }}'
)
conn.cursor().execute('USE DATABASE ${{ secrets.SNOWFLAKE_DATABASE }}')
conn.cursor().execute('USE SCHEMA ${{ secrets.SNOWFLAKE_SCHEMA }}')
conn.cursor().execute('USE WAREHOUSE ${{ secrets.SNOWFLAKE_WAREHOUSE }}')
with open('your_script.sql', 'r') as file:
    sql_script = file.read()
for stmt in sql_script.split(';'):
    if stmt.strip():
        conn.cursor().execute(stmt)
conn.close()
"
